//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MudCeramWorkshop.Client.Components.Layout.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuTranslation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuTranslation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MudCeramWorkshop.Client.Components.Layout.Resources.MenuTranslation", typeof(MenuTranslation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessoires.
        /// </summary>
        public static string NavMenu_Accessory {
            get {
                return ResourceManager.GetString("NavMenu_Accessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argiles.
        /// </summary>
        public static string NavMenu_Clays {
            get {
                return ResourceManager.GetString("NavMenu_Clays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes cuissons.
        /// </summary>
        public static string NavMenu_Firing {
            get {
                return ResourceManager.GetString("NavMenu_Firing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Émaux.
        /// </summary>
        public static string NavMenu_Glaze {
            get {
                return ResourceManager.GetString("NavMenu_Glaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon inventaire.
        /// </summary>
        public static string NavMenu_MyInventory {
            get {
                return ResourceManager.GetString("NavMenu_MyInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes produits.
        /// </summary>
        public static string NavMenu_MyProducts {
            get {
                return ResourceManager.GetString("NavMenu_MyProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignOut.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
    }
}
