//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MudCeramWorkshop.Client.Components.Pages.ProductPages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductTranslation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductTranslation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MudCeramWorkshop.Client.Components.Pages.ProductPages.Resources.ProductTranslatio" +
                            "n", typeof(ProductTranslation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir.
        /// </summary>
        public static string ProductList_ShowProduct {
            get {
                return ResourceManager.GetString("ProductList_ShowProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ø Bottom.
        /// </summary>
        public static string Text_BottomDiameter {
            get {
                return ResourceManager.GetString("Text_BottomDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction de construction.
        /// </summary>
        public static string Text_BuildInstructions {
            get {
                return ResourceManager.GetString("Text_BuildInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaire.
        /// </summary>
        public static string Text_Comment {
            get {
                return ResourceManager.GetString("Text_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition.
        /// </summary>
        public static string Text_Composition {
            get {
                return ResourceManager.GetString("Text_Composition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail des coûts.
        /// </summary>
        public static string Text_CostDetails {
            get {
                return ResourceManager.GetString("Text_CostDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Text_Description {
            get {
                return ResourceManager.GetString("Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions de conception.
        /// </summary>
        public static string Text_DesignInstructions {
            get {
                return ResourceManager.GetString("Text_DesignInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glisser et déposer les fichiers ici ou cliquer.
        /// </summary>
        public static string Text_DragAndDrop {
            get {
                return ResourceManager.GetString("Text_DragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions d&apos;émaillage.
        /// </summary>
        public static string Text_GlazingInstructions {
            get {
                return ResourceManager.GetString("Text_GlazingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauteur.
        /// </summary>
        public static string Text_Height {
            get {
                return ResourceManager.GetString("Text_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix de vente.
        /// </summary>
        public static string Text_SellingPrice {
            get {
                return ResourceManager.GetString("Text_SellingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ø Top.
        /// </summary>
        public static string Text_TopDiameter {
            get {
                return ResourceManager.GetString("Text_TopDiameter", resourceCulture);
            }
        }
    }
}
