services:

  mudceramworkshop.client:
    image: ${DOCKER_REGISTRY-}mudceramworkshopclient
    container_name: mudceramworkshop.client
    user: "root"

    networks:
      testnet:
        ipv4_address: 172.26.0.38
    ports:
      - "9090:9090"
    restart: always

    build:
      context: ..
      dockerfile: ./MudCeramWorkshop.Client/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_Kestrel__Endpoints__Https__Url=https://*:443
      # - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/app/certs/fullchain.pem
      # - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__KeyPath=/app/certs/privkey.pem
    depends_on:
      - mudceramworkshop.data
    volumes:
      - /home/data/client:/app/data:ro
      # - /etc/letsencrypt/live/workshop.atelier-cremazie.com/fullchain.pem:/app/certs/fullchain.pem:ro
      # - /etc/letsencrypt/live/workshop.atelier-cremazie.com/privkey.pem:/app/certs/privkey.pem:ro

  mudceramworkshop.data:
    image: postgres:latest
    container_name: mudceramworkshop.data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: PGUserPwd
      POSTGRES_DB: ceramworkshopdb
    volumes:
      - /home/data/db:/var/lib/postgresql/data

    networks:
      testnet:
        ipv4_address: 172.26.0.39
    ports:
      - "5432:5432"
    restart: always
        
networks:
  testnet:
    external: true