services:
  mudceramworkshop.client:
    ports:
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_Kestrel__Endpoints__Https__Url=https://*:443
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/app/certs/fullchain.pem
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__KeyPath=/app/certs/privkey.pem
    volumes:
      - /etc/letsencrypt/live/workshop.atelier-cremazie.com/fullchain.pem:/app/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/workshop.atelier-cremazie.com/privkey.pem:/app/certs/privkey.pem:ro
