services:

  mudceramworkshop.client:
    image: ${DOCKER_REGISTRY-}mudceramworkshopclient
    container_name: mudceramworkshop.client
    ports:
      - "80:80"  # Expose le port 80 de l'hote vers le port 80 du conteneur
    build:
      context: .
      dockerfile: MudCeramWorkshop.Client/Dockerfile
    depends_on:
      - mudceramworkshop.data
- 
  mudceramworkshop.data:
    image: postgres:latest
    container_name: mudceramworkshop.data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: PGUserPwd
      POSTGRES_DB: ceramworkshopdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: