services:

  mudceramworkshop.client:
    image: ${DOCKER_REGISTRY-}mudceramworkshopclient
    container_name: mudceramworkshop.client
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: MudCeramWorkshop.Client/Dockerfile
    depends_on:
      - mudceramworkshop.data
    volumes:
      - /home/data/client:/app/data  # Mapping du volume

  mudceramworkshop.data:
    image: postgres:latest
    container_name: mudceramworkshop.data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: PGUserPwd
      POSTGRES_DB: ceramworkshopdb
    volumes:
      - /home/data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"